name: built_redux_saga
description: Provides support for handling built_redux middleware using sagas.
version: 1.0.19
homepage: https://github.com/guypeled76
author: Guy Peled <guypeled76@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  built_collection: '>=2.0.0 <5.0.0'
  built_value: '>=5.5.5 <7.0.0'
  built_redux: ^7.5.4
#    git: https://github.com/guypeled76/built_redux

dev_dependencies:
  build_runner: ^1.0.0
  built_value_generator: ^6.3.0
  json_serializable: ^2.0.1
  pedantic: ^1.0.0
  test: ^1.0.0
